### ISSUE TITLE
Remember size and position of each note on screen

### ISSUE THREAD

**Issue by seanh** [vixalien/sticky#12]
... after quitting and restarting the app.

Thanks!

Lovely little app by the way

**Comment by vixalien** [comment]
the size of position is remember, but not the position.

this is because on Wayland, windows cannot "see" outside their own window.
this means that windows cannot calculate their position in relation to the
monitor/screen because of security reasons.

it's definitely possible for X11, but I'm not sure to implement
X11-specific features

**Comment by fabd** [comment]
That's a bummer.

The next option could be to remember and restore the position of the main window itself. Then, when the logic decides to show a sticky upon start (it does that for me when I close the main window, and have one sticky open, and then close the app and restart it) - then in that case you could place the sticky to where the main window was?

This would allow to at least have the last visible sticky when the app was closed to be restored to its original position - so long as the user found out that he/she can use the main window as a guide.

**Comment by vixalien** [comment]
that's not possible either. as I said, wayland app windows are extremely sandboxed and as such can not know where they are placed in relation to the screen (i.e they can't know where they are placed on the screen, as they cannot "see" outside their won windows).

it's hard, but can be implemented:

- X isn't as sandboxed as Wayland and apps can freely interact with everything by default so that may be feasible on X, however I'm not planning to implement this as X users are a minority and I'm not willing to write X-specific code :)
- Use the [Smart Auto Move](https://extensions.gnome.org/extension/4736/smart-auto-move/) extension for GNOME and limit it only to Sticky Notes if you like (NOT TESTED)
