### ISSUE TITLE
Switch between light and dark versions manually

### ISSUE THREAD

**Issue by jasiralavibiztripz** [vixalien/sticky#15]
I have dark theme by default, Is there a way to switch to light version manually?
I think this should be an option along with font selection.

I've been using xpad for years now, like how I can configure it to show on desktop without window decorations and options to custom select fonts and colors. Is this something you're planning?

**Comment by vixalien** [comment]
I think custom fonts would be overkill. since the app uses your systems default font.

what do you mean without window decorations? like a free-floating borderless window?

and about light and dark theme. I think this would be confusing since the user's will have to choose between styles (blue, yellow etc) and themes (light, dark, etc)

**Comment by vixalien** [comment]
I think custom fonts would be overkill. since the app uses your systems default font.

what do you mean without window decorations? like a free-floating borderless window?

and about light and dark theme. I think this would be confusing since the user's will have to choose between styles (blue, yellow etc) and themes (light, dark, etc).

**Comment by vixalien** [comment]
fixed by https://github.com/vixalien/sticky/commit/7e5516656b0bb86b9f863d4bc249e58b731685f2
