### ISSUE TITLE
Dark mode looks a bit broken

### ISSUE THREAD

**Issue by leolost2605** [vixalien/sticky#21]
Hi, first of all i want to say great app and in light mode it is awesome!

But in my opinion dark mode looks a bit broken. Are there any plans to revamp it?

Otherwise a manual light - dark toggle as suggested in #15 would be nice to have... maybe in the global menu of the main window where it doesn't conflict with the color chooser?

Anyway other than that thanks for your great work with this app!

**Comment by vixalien** [comment]
if you think a revamp is necessary, what design do you propose?

i modeled the current dark mode from the windows' sticky notes so I think it looks fine. do you have any recommendations on how I can fix it?

**Comment by vixalien** [comment]
fixed by https://github.com/vixalien/sticky/commit/7e5516656b0bb86b9f863d4bc249e58b731685f2

**Comment by istvan-derda** [comment]
Hi, I like the app a lot too, I think it looks amazing! Except I was also a bit surprised, when I switched to dark mode. I think it looks a bit off, because the headerbars of the notes collaps when they are not active, so you are left with a thin stripe of bright color on the otherwise black note. My suggestion would be to just leave the notes fully colored in darkmode too and just have the white background of the main app be affected and change to dark (hard to do design-recommendations in text)

As long as it is this way I'm fine with just hard-setting the app to always use the light-mode.

**Comment by vixalien** [comment]
the thing is that with the current pastel colors, the notes are extremely
bright in dark mode if you leave the background colour as the pastel color,
which is the reason I went for the current look.

it's possible to disable the headerbar collapsing though
