### ISSUE TITLE
Issue with Dark mode!

### ISSUE THREAD

**Issue by sajidzaman** [vixalien/sticky#31]
![sticky-issuewithdarkmode1](https://user-images.githubusercontent.com/5072833/224246287-aa1107df-6ec8-4553-a9f1-a2335c65f879.png)
![sticky-issuewithdarkmode](https://user-images.githubusercontent.com/5072833/224246291-b3567650-e0e6-4c63-a7a9-e300a3868ba0.png)

When using the dark mode in Gnome 43, The background of the sticky notes becomes black. In the Light mode it works fine. Screenshots attached.

**Comment by vixalien** [comment]
Hello! I see this issue being brought up a lot (see #21 #15) so it might indeed be broken.

how do you expect it to look like?? the reason why dark mode looks like so is because otherwise the bright pastel colors look too bright on dark mode.

I can fix this, but I need to know what to fix. here's some ideas:

- make the notes have the bright colors as background color in dark mode eitherway, I don't care if it's too bright
- use more dark colors as background colors in dark mode
- disable the headerbar collapsing
- more suggestions...

**Comment by sajidzaman** [comment]
The easiest option should be.
We can choose the colors which are perfect fit for both dark mode and light mode. Neither too bright nor too light.
Or 
As Sticky allows user to change the colors. Both light mode and dark mode colors can be listed in the color dialog can also be an option. Some people do prefer bright colors in dark mode as well, so may be allow both of them in selection.

**Comment by vixalien** [comment]
okay I got it. I'll implement somewhat darker colors for dark mode

by the way, you can choose sticky notes to always be light independent of system preferences in the all notes window.

![image](https://user-images.githubusercontent.com/37999241/224283879-33f9e849-2a12-4af8-aa8c-644b4a10e474.png)

**Comment by vixalien** [comment]
well this turned out harder than I initially thought lol.

I can't just do `darken(color, 70%)`, someone with good design/color skills will have to chip in

**Comment by sajidzaman** [comment]
@vixalien I am currently using the app in light mode to avoid the dark mode issue as you mentioned above.

I have contacted one of my colleague,He might come up with some solution

**Comment by vixalien** [comment]
cool. might want to point them to this file https://github.com/vixalien/sticky/blob/main/data/stylus/colors.styl

the keys are as follows:

- **bg** the background color
- **header** the background of the header bar (the headerbar is slightly darker)
- **ink** selection background color
- **hc** high contrast color

they probably need to create a new color `dark-bg` which is a variant of `bg`
