### ISSUE TITLE
Add a title to a sticky note

### ISSUE THREAD

**Issue by Nokse22** [vixalien/sticky#40]
The top left of the note when closed fells a little empty.
I would suggest adding the possibility to add a title to every note. Maybe with a dedicated text box when a note is opened or using markdown, like if there is a # in the first line the text after it becomes the title

![Screenshot from 2023-03-22 11-36-56](https://user-images.githubusercontent.com/44558032/226877966-bede4786-b68e-4d43-ab4b-6d9b69a33f34.png)
This above is a concept

**Comment by Nokse22** [comment]
Maybe like this? I don't know how the title feature could work tho.

For sure I you put the edit button on the left it would feel less empty.
![Screenshot from 2023-03-22 11-36-56](https://user-images.githubusercontent.com/44558032/227140823-aece6567-e71f-44b7-9087-88f219217b33.png)

**Comment by JamesL813** [comment]
I think this is a good idea and could help make the header bars in the note window look less empty. Especially when unfocused.

![title_focused](https://user-images.githubusercontent.com/57780020/227264272-198ab35e-0f3a-43b1-87cd-2e23c5fa6fe2.png)
![title_unfocused](https://user-images.githubusercontent.com/57780020/227264297-49f907f6-a667-46a7-9a23-9b1dc3da6793.png)

Not sure the best way to implement this intuitively, though. I don't love the idea of the title bar being clicked on to edit, like in gnome-notes. I found it kind of annoying seeing a text box with "Untitled" on every new note. What I like about Sticky Notes is how clean it looks and how easy it is to quickly make new notes.

![Screenshot from 2023-03-23 12-21-26](https://user-images.githubusercontent.com/57780020/227268923-2be294a4-bc8d-4a87-a73c-214a38876e2d.png)

If you choose to implement something like this, I think it should be optional and non-intrusive. A few possible ideas:

- If the first line is bold or has a "#" before it, it becomes the title as mentioned above
- In the note window there's a "✏️" button on the header bar, or an "edit title" button in the hamburger menu
- Title can be edited in the main window
(Something like this?)

![menu-titles](https://user-images.githubusercontent.com/57780020/227272659-4605f12d-4ce2-48d5-8162-4aefbcecb1e9.png)

Although this does kind of conflict with the previous comment. I personally think a single or double-click on the main text is intuitive enough that an "edit note" button is unnecessary, but that's just me.

Anyway, sorry for the long comment, lol. LMK your thoughts!

**Comment by vixalien** [comment]
hey there James. here's my notes:

1. in the first mockup, note that the title will be CENTERED, not aligned to the left. hence the title will be truncated much more often (long titles are a no-go)
2. if I make it so that the first text that starts with a "#" is a title, does that mean that it is automatically removed from the body of the note, then put into the title? Or does it stay there?
3. The "edit" button in the all notes window is kinda ambigous because at first look it seems that it's to open the NOTE, and not the TITLE

**Comment by vixalien** [comment]
conveniently enough, there is a `Gtk.EditableLabel` widget that can handle this for us quite gracefully...

however, there are some caveats right now:

1.when the title content is too long, the note window expands (can be solved either by allowing this if it's the desired behavior, or ellipsing the text)
2. the app won't be draggable using the headerbar, since the editablelabel will handle the drag events (can be solved by requiring a double tap to edit the label, but this is not something easy to do, and might break mobile support)
3. this still doesn't solve how it might appear in the "all notes" view

also note that the note will STILL be ellipsised even when it's not focus (i.e when the window decorations (close, menu, new note) are not visible)

here's a video of how it would look like if implemented

[Screencast from 2023-03-24 22-47-28.webm](https://user-images.githubusercontent.com/37999241/227638204-e4fb9189-9bec-4675-98b3-2c91ab89de5e.webm)

**Comment by vixalien** [comment]
also forgot to note that for users with multiple window decorations (close, minimise, maximise) the label will have very little space (don't know if it's really a problem though)

**Comment by JamesL813** [comment]
Yeah, dragging the app should definitely be a priority.

To me, an "Edit Note Title" option in the main menu button for individual notes, and regular text boxes for notes in the main window seem like the next best solutions.

**Comment by vixalien** [comment]
to be honest I'm not really sure right now if we really need to have a title for notes.

this is because 1. there's no intuitive way to do it and 2. the size constraints

for example, in the all notes view, there will be an edit note button (see #34 ) and in the notes window there could be a pin button (see #39 )

and you can have functioning titles by effectively boldening your first line and it will appear in the all notes window, so I think this is pretty unnecessary and hard to implement

**Comment by fwinkl** [comment]
I came across this feature request while migrating from xpad to this app. xpad handles this very similar to this suggestion:
> If the first line is bold or has a "#" before it, it becomes the title as mentioned above

(it doesn't require any special formatting though). The first line then simply becomes the gnome window title. And yes, if window decorations are used, the text appears both in the window title and as part of the body:

![Screenshot from 2024-01-09 11-18-27](https://github.com/vixalien/sticky/assets/17143026/9c989517-9b64-4409-b733-a4773928bca0)

 But I don't think that's an issue. It makes finding notes via the window list much easier though as you can see in the following screenshot comparison (xpad also doesn't have a main overview window):

| ![Screenshot from 2024-01-09 11-07-23](https://github.com/vixalien/sticky/assets/17143026/9d7f9f3f-62eb-4fde-9348-1854ff2e87a5) | ![Screenshot from 2024-01-09 11-07-07](https://github.com/vixalien/sticky/assets/17143026/bad990c0-d650-4bb1-ace4-ccf34f26da00) |

Maybe this minimal option that doesn't require any new UI elements could still be considered.

**Comment by vixalien** [comment]
@fwinkl I like your proposal. I'll definitely start looking into the implementation

**Comment by TriVoxel** [comment]
I actually came here to propose this feature... So glad to see it's already planned!

**Comment by TriVoxel** [comment]
> to be honest I'm not really sure right now if we really need to have a title for notes.
> 
> this is because 1. there's no intuitive way to do it and 2. the size constraints
> 
> for example, in the all notes view, there will be an edit note button (see #34 ) and in the notes window there could be a pin button (see #39 )
> 
> and you can have functioning titles by effectively boldening your first line and it will appear in the all notes window, so I think this is pretty unnecessary and hard to implement

What about instead of a label that can be renamed with an icon, or by clicking the text, new notes could have a basic, centered button with some text like "Name note", which can popup a little modal to set the name. Once created, the button goes away, and the standard LibAdwaita window title is used? There could be a "Rename" button in the "Main Menu" of the note, and something like this context menu I mocked up could be used to rename it in the main app: #115?

**Comment by vixalien** [comment]
The title is now the first few words of the note after #143
