### ISSUE TITLE
[FR] Store the notes in a user visible folder, so they can be synced

### ISSUE THREAD

**Issue by lobau** [vixalien/sticky#51]
I use dropbox to sync many things, but the service I use is irrelevant.
If sticky notes allowed me to point at a folder in which the notes are stores as .txt or .md files, I could store this folder in my dropbox and access the notes everywhere.
It would also allow me to open the same folder in another app, like Paper or Inkdrop, to achieve total data portability!

**Comment by JamesL813** [comment]
From what I know, the app stores its notes in `json` files that store the note itself as a string, metadata, plus styling information, like if a section is **bold** it stores where the bold text starts and ends. This means that while it could possibly store the content as a reference to another file rather than a string, it wouldn't be able to preserve formatting if another program edited or moved the file. 

But I like this idea too, and I'd be willing to give up formatting for certain apps in order to sync them with Nextcloud. I'm not sure of a good way to make this work intuitively, though.

**Comment by lobau** [comment]
I'll be honest, to me, that means that if tomorrow I want to move my notes to another app, I will lose data (even if it's just formatting data). Having interoperability (even if just an export) is important to me (some random user feedback for you :))

**Comment by vixalien** [comment]
well the notes store the app inn a standard location, but that location can be different.

https://github.com/vixalien/sticky/blob/76862adfcda58c616fc2a8b999c1f04fe5850bc6/src/store.ts#L42

in the future, I want for the app to log what that location is so that you could sync the notes (copy pasting all the files in the directory to another stick notes's saving directory will work).

but I'm not sure if this accommodate your needs, in which case sticky can be made to have a configurable storage directory.

it may also be useful to have an export/import thing but that seems not very useful for me at the moment (e.g would it export markdown or the raw JSON) so if you have a use case please tell me.

**Comment by vixalien** [comment]
On the latest sticky notes, the app will log where it stores the notes (may vary based on flatpak, distro etc) and you can use that folder to sync notes. I will be closing this soon as solved if there's no further comment.

**Comment by lobau** [comment]
Sounds great, thanks!

**Comment by McBaumwolle** [comment]
Okay quick question, is there any possibility to change where the data is stored, maybe with some config files? Unfortunately, I cannot sync my notes to Nextcloud because the directory is not accessible.

![Image](https://github.com/user-attachments/assets/dafaa897-b4cf-45ba-923c-669cc2b9ed76)

**Comment by vixalien** [comment]
> is there any possibility to change where the data is stored

Not currently, but I'll work on it
