### ISSUE TITLE
[Feature Request] Ability to Permanently Enable “Always on Top” and “Always on Visible Workspace”

### ISSUE THREAD

**Issue by julianschacher** [vixalien/sticky#93]
It would be cool, if one could enable the "Always on Top" and "Always on Visible Workspace" options in a permanent manner.
While it is possible to set those settings for a note, once one closes the note, the settings are forgotten. Being able to set those options permanently would be awesome and would really add to the sticky notes character, since those would typically be on top of the monitor and not disappear when switching workspaces.

**Comment by vixalien** [comment]
see #39 and https://discourse.gnome.org/t/gtk4-set-window-always-on-top-and-on-center-of-current-monitor/9068

tldr: it's simply not possible because of the way Wayland works. it's actually a good feature tho, because in Wayland windows cannot see outside their windows and hence privacy is respected. that means that the only thing that knows your screen size and how to position window is your display manager.
